# Generated by Django 5.2.4 on 2025-08-06 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='planes/')),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DatosUEB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('enero', models.FloatField(blank=True, null=True)),
                ('febrero', models.FloatField(blank=True, null=True)),
                ('marzo', models.FloatField(blank=True, null=True)),
                ('abril', models.FloatField(blank=True, null=True)),
                ('mayo', models.FloatField(blank=True, null=True)),
                ('junio', models.FloatField(blank=True, null=True)),
                ('julio', models.FloatField(blank=True, null=True)),
                ('agosto', models.FloatField(blank=True, null=True)),
                ('septiembre', models.FloatField(blank=True, null=True)),
                ('octubre', models.FloatField(blank=True, null=True)),
                ('noviembre', models.FloatField(blank=True, null=True)),
                ('diciembre', models.FloatField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uebs', to='planes.plan')),
            ],
        ),
        migrations.CreateModel(
            name='DatosMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('enero', models.FloatField(blank=True, null=True)),
                ('febrero', models.FloatField(blank=True, null=True)),
                ('marzo', models.FloatField(blank=True, null=True)),
                ('abril', models.FloatField(blank=True, null=True)),
                ('mayo', models.FloatField(blank=True, null=True)),
                ('junio', models.FloatField(blank=True, null=True)),
                ('julio', models.FloatField(blank=True, null=True)),
                ('agosto', models.FloatField(blank=True, null=True)),
                ('septiembre', models.FloatField(blank=True, null=True)),
                ('octubre', models.FloatField(blank=True, null=True)),
                ('noviembre', models.FloatField(blank=True, null=True)),
                ('diciembre', models.FloatField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='planes.plan')),
            ],
        ),
    ]
