# Generated by Django 5.2.4 on 2025-08-12 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosmunicipio',
            options={'verbose_name': 'Datos Municipio', 'verbose_name_plural': 'Datos Municipios'},
        ),
        migrations.AlterModelOptions(
            name='datosueb',
            options={'verbose_name': 'Datos UEB', 'verbose_name_plural': 'Datos UEBs'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-fecha_carga'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AddField(
            model_name='datosmunicipio',
            name='es_mensual',
            field=models.BooleanField(default=False, verbose_name='¿Es dato mensual?'),
        ),
        migrations.AddField(
            model_name='datosmunicipio',
            name='obet',
            field=models.CharField(blank=True, choices=[('OBET Colón', 'OBET Colón (Calimete, Los Arabos, Martí, Colón)'), ('OBET Jagüey', 'OBET Jagüey (Jagüey Grande, Pedro Betancourt, Ciénaga de Zapata)'), ('OBET Unión', 'OBET Unión de Reyes (Unión de Reyes, Limonar)'), ('OBET Matanzas', 'OBET Matanzas (Matanzas)'), ('OBET Jovellanos', 'OBET Jovellanos (Jovellanos, Perico)'), ('OBET Cárdenas', 'OBET Cárdenas (Cárdenas)'), ('OBET Varadero', 'OBET Varadero (Varadero)')], max_length=50, verbose_name='OBET Relacionado'),
        ),
        migrations.AddField(
            model_name='datosueb',
            name='es_mensual',
            field=models.BooleanField(default=False, verbose_name='¿Es dato mensual?'),
        ),
        migrations.AlterField(
            model_name='datosmunicipio',
            name='enero',
            field=models.FloatField(blank=True, null=True, verbose_name='Enero (%)'),
        ),
        migrations.AlterField(
            model_name='datosmunicipio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='datosueb',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='UEB/OBET'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='archivo',
            field=models.FileField(upload_to='planes/', verbose_name='Archivo Excel'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fecha_carga',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Carga'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='periodo',
            field=models.CharField(max_length=100, verbose_name='Período del Plan'),
        ),
    ]
