# Generated by Django 5.2.4 on 2025-08-12 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_alter_datosmunicipio_options_alter_datosueb_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosmunicipio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datosueb',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.AlterField(
            model_name='datosmunicipio',
            name='enero',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datosmunicipio',
            name='es_mensual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datosmunicipio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datosmunicipio',
            name='obet',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='datosueb',
            name='es_mensual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datosueb',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='archivo',
            field=models.FileField(upload_to='planes/'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fecha_carga',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plan',
            name='periodo',
            field=models.CharField(max_length=100),
        ),
    ]
