# Generated by Django 5.2.4 on 2025-08-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturacionMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(choices=[('MAT', 'Matanzas'), ('VAR', 'Varadero'), ('CAR', 'Cárdenas'), ('MAR', 'Martí'), ('PER', 'Perico'), ('ARA', 'Arabos'), ('COL', 'Colón'), ('JOV', 'Jovellanos'), ('BET', 'Betancourt'), ('UNI', 'Unión de Reyes'), ('LIM', 'Limonar'), ('CIE', 'Ciénaga de Zapata'), ('JG', 'Jagüey Grande'), ('CAL', 'Calimete')], max_length=3)),
                ('mes', models.PositiveSmallIntegerField()),
                ('año', models.PositiveSmallIntegerField()),
                ('facturacion_mayor', models.FloatField()),
                ('facturacion_menor', models.FloatField()),
                ('total_facturado', models.FloatField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['año', 'mes', 'municipio'],
                'unique_together': {('municipio', 'mes', 'año')},
            },
        ),
    ]
