# Generated by Django 5.2.4 on 2025-08-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacionmunicipio',
            name='consumo_transmision',
            field=models.FloatField(default=0.0),
        ),
    ]
