# Generated by Django 5.2.4 on 2025-08-12 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obet', models.CharField(choices=[('OBET Colón', 'OBET Colón (Calimete, Los Arabos, Martí, Colón)'), ('OBET Jagüey', 'OBET Jagüey (Jagüey Grande, Pedro Betancourt, Ciénaga de Zapata)'), ('OBET Unión', 'OBET Unión de Reyes (Unión de Reyes, Limonar)'), ('OBET Matanzas', 'OBET Matanzas (Matanzas)'), ('OBET Jovellanos', 'OBET Jovellanos (Jovellanos, Perico)'), ('OBET Cárdenas', 'OBET Cárdenas (Cárdenas)'), ('OBET Varadero', 'OBET Varadero (Varadero)')], max_length=20)),
                ('municipio', models.CharField(choices=[('MAT', 'Matanzas'), ('VAR', 'Varadero'), ('CAR', 'Cárdenas'), ('MAR', 'Martí'), ('PER', 'Perico'), ('ARA', 'Los Arabos'), ('COL', 'Colón'), ('JOV', 'Jovellanos'), ('BET', 'Pedro Betancourt'), ('UNI', 'Unión de Reyes'), ('LIM', 'Limonar'), ('CIE', 'Ciénaga de Zapata'), ('JG', 'Jagüey Grande'), ('CAL', 'Calimete')], max_length=3)),
                ('fecha', models.DateField()),
                ('consumo', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consumo de Energía',
                'verbose_name_plural': 'Consumos de Energía',
                'db_table': 'perdidas_consumoenergia',
                'ordering': ['fecha', 'obet'],
                'unique_together': {('municipio', 'fecha')},
            },
        ),
    ]
