# Generated by Django 5.2.4 on 2025-08-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoenergia',
            name='municipio',
            field=models.CharField(choices=[('MAT', 'Matanzas'), ('VAR', 'Varadero'), ('CAR', 'Cárdenas'), ('MAR', 'Martí'), ('PER', 'Perico'), ('ARA', 'Los Arabos'), ('COL', 'Colón'), ('JOV', 'Jovellanos'), ('BET', 'Pedro Betancourt'), ('UNI', 'Unión de Reyes'), ('LIM', 'Limonar'), ('CIE', 'Ciénaga de Zapata'), ('JG', 'Jagüey Grande'), ('CAL', 'Calimete')], max_length=3),
        ),
    ]
