# Generated by Django 5.2.4 on 2025-08-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perdidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consumoenergia',
            table='perdidas_consumo_energia',
        ),
    ]
