# Generated by Django 5.2.4 on 2025-08-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perdidas', '0002_alter_consumoenergia_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consumoenergia',
            table='perdidas_consumoenergia',
        ),
    ]
