# Generated by Django 5.2.4 on 2025-08-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perdidas', '0002_alter_consumoenergia_municipio'),
        ('perdidas', '0003_alter_consumoenergia_table'),
    ]

    operations = [
    ]
