# Generated by Django 5.2.4 on 2025-08-06 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPerdidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(choices=[('MAT', 'Matanzas'), ('VAR', 'Varadero'), ('CAR', 'Cárdenas'), ('MAR', 'Martí'), ('PER', 'Perico'), ('ARA', 'Arabos'), ('COL', 'Colón'), ('JOV', 'Jovellanos'), ('BET', 'Betancourt'), ('UNI', 'Unión de Reyes'), ('LIM', 'Limonar'), ('CIE', 'Ciénaga de Zapata'), ('JG', 'Jagüey Grande'), ('CAL', 'Calimete')], max_length=3, verbose_name='Municipio')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('año', models.PositiveSmallIntegerField()),
                ('energia_barra', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Energía en Barra (MWh)')),
                ('total_ventas', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Facturado (MWh)')),
                ('perdidas_mwh', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pérdidas (MWh)')),
                ('perdidas_pct', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pérdidas (%)')),
                ('acumulado_energia', models.FloatField(default=0)),
                ('acumulado_perdidas', models.FloatField(default=0)),
                ('acumulado_pct', models.FloatField(default=0)),
                ('acumulado_ventas', models.FloatField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('facturacion_mayor', models.FloatField(default=0)),
                ('facturacion_menor', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Resultado de Pérdidas',
                'verbose_name_plural': 'Resultados de Pérdidas',
                'db_table': 'infoperdidas_municipio',
                'ordering': ['año', 'mes', 'municipio'],
                'indexes': [models.Index(fields=['municipio'], name='infoperdida_municip_81fab7_idx'), models.Index(fields=['mes'], name='infoperdida_mes_22e356_idx'), models.Index(fields=['año'], name='infoperdida_año_48e70f_idx')],
                'unique_together': {('municipio', 'mes', 'año')},
            },
        ),
    ]
