# Generated by Django 5.2.4 on 2025-08-02 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoperdidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoperdidas',
            name='acumulado_ventas',
            field=models.FloatField(default=0, verbose_name='Ventas Acumuladas (MWh)'),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='acumulado_energia',
            field=models.FloatField(default=0, verbose_name='Energía Acumulada (MWh)'),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='acumulado_pct',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pérdidas Acumuladas (%)'),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='acumulado_perdidas',
            field=models.FloatField(default=0, verbose_name='Pérdidas Acumuladas (MWh)'),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='facturacion_mayor',
            field=models.FloatField(default=0, verbose_name='Facturación Mayorista (MWh)'),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='facturacion_menor',
            field=models.FloatField(default=0, verbose_name='Facturación Minorista (MWh)'),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='municipio',
            field=models.CharField(choices=[('MAT', 'Matanzas'), ('VAR', 'Varadero'), ('CAR', 'Cárdenas'), ('MAR', 'Martí'), ('PER', 'Perico'), ('ARA', 'Arabos'), ('COL', 'Colón'), ('JOV', 'Jovellanos'), ('BET', 'Betancourt'), ('UNI', 'Unión de Reyes'), ('LIM', 'Limonar'), ('CIE', 'Ciénaga de Zapata'), ('JG', 'Jagüey Grande'), ('CAL', 'Calimete'), ('PRO', 'PROVINCIA')], max_length=3, verbose_name='Municipio'),
        ),
        migrations.AddIndex(
            model_name='resultadoperdidas',
            index=models.Index(fields=['año', 'mes'], name='infoperdida_año_362434_idx'),
        ),
    ]
