# Generated by Django 5.2.4 on 2025-08-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoperdidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoperdidas',
            name='plan_acum_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resultadoperdidas',
            name='plan_pct',
            field=models.FloatField(default=0),
        ),
    ]
