# Generated by Django 5.2.4 on 2025-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoperdidas', '0002_resultadoperdidas_plan_acum_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='municipio',
            field=models.CharField(choices=[('MAT', 'Matanzas'), ('VAR', 'Varadero'), ('CAR', 'Cárdenas'), ('MAR', 'Martí'), ('PER', 'Perico'), ('ARA', 'Arabos'), ('COL', 'Colón'), ('JOV', 'Jovellanos'), ('BET', 'Betancourt'), ('UNI', 'Unión de Reyes'), ('LIM', 'Limonar'), ('CIE', 'Ciénaga de Zapata'), ('JG', 'Jagüey Grande'), ('CAL', 'Calimete'), ('PROVINCIA', 'PROVINCIA')], max_length=10, verbose_name='Municipio'),
        ),
    ]
