# Generated by Django 5.2.4 on 2025-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoperdidas', '0002_resultadoperdidas_acumulado_ventas_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resultadoperdidas',
            name='infoperdida_año_362434_idx',
        ),
        migrations.RemoveField(
            model_name='resultadoperdidas',
            name='acumulado_ventas',
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='acumulado_energia',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='acumulado_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='acumulado_perdidas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='facturacion_mayor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='facturacion_menor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resultadoperdidas',
            name='municipio',
            field=models.CharField(choices=[('MAT', 'Matanzas'), ('VAR', 'Varadero'), ('CAR', 'Cárdenas'), ('MAR', 'Martí'), ('PER', 'Perico'), ('ARA', 'Arabos'), ('COL', 'Colón'), ('JOV', 'Jovellanos'), ('BET', 'Betancourt'), ('UNI', 'Unión de Reyes'), ('LIM', 'Limonar'), ('CIE', 'Ciénaga de Zapata'), ('JG', 'Jagüey Grande'), ('CAL', 'Calimete')], max_length=3, verbose_name='Municipio'),
        ),
    ]
